# Generated by Django 4.2.2 on 2023-07-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
